[build]
  publish = "wwwroot"  # Static files are in the wwwroot folder

[[redirects]]
  from = "/auth"
  to = "/routes/auth.js"
  status = 200

[[redirects]]
  from = "/export"
  to = "/routes/export.js"
  status = 200

[[redirects]]
  from = "/hubs"
  to = "/routes/hubs.js"
  status = 200

[[redirects]]
  from = "/services/aps"
  to = "/services/aps.js"
  status = 200
